# Generated by Django 5.1.1 on 2024-09-16 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('attempt', models.IntegerField(default=0, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('optional', models.IntegerField(choices=[(0, 'Not Selected'), (1, 'Agriculture'), (2, 'Animal Husbandry and Veterinary Science'), (3, 'Anthropology'), (4, 'Botany'), (5, 'Chemistry'), (6, 'Civil Engineering'), (7, 'Commerce & Accountancy'), (8, 'Economics'), (9, 'Electrical Engineering'), (10, 'Geography'), (11, 'Geology'), (12, 'History'), (13, 'Law'), (14, 'Management'), (15, 'Mathematics'), (16, 'Mechanical Engineering'), (17, 'Medical Science'), (18, 'Philosophy'), (19, 'Physics'), (20, 'Political Science & International Relations'), (21, 'Psychology'), (22, 'Public Administration'), (23, 'Sociology'), (24, 'Statistics'), (25, 'Zoology'), (26, 'Hindi Literature'), (27, 'Assamese Literature'), (28, 'Bengali Literature'), (29, 'Bodo Literature'), (30, 'Dogri Literature'), (31, 'Gujarati Literature'), (32, 'Kannada Literature'), (33, 'Kashmiri Literature'), (34, 'Konkani Literature'), (35, 'Maithili Literature'), (36, 'Malayalam Literature'), (37, 'Manipuri Literature'), (38, 'Marathi Literature'), (39, 'Nepali Literature'), (40, 'Oriya Literature'), (41, 'Punjabi Literature'), (42, 'Sanskrit Literature'), (43, 'Santhali Literature'), (44, 'Sindhi Literature'), (45, 'Tamil Literature'), (46, 'Telugu Literature'), (47, 'Urdu Literature'), (48, 'English Literature')], default=0)),
                ('state', models.IntegerField(choices=[(0, 'Not Selected'), (1, 'Andhra Pradesh'), (2, 'Arunachal Pradesh'), (3, 'Assam'), (4, 'Bihar'), (5, 'Chhattisgarh'), (6, 'Goa'), (7, 'Gujarat'), (8, 'Haryana'), (9, 'Himachal Pradesh'), (10, 'Jharkhand'), (11, 'Karnataka'), (12, 'Kerala'), (13, 'Madhya Pradesh'), (14, 'Maharashtra'), (15, 'Manipur'), (16, 'Meghalaya'), (17, 'Mizoram'), (18, 'Nagaland'), (19, 'Odisha'), (20, 'Punjab'), (21, 'Rajasthan'), (22, 'Sikkim'), (23, 'Tamil Nadu'), (24, 'Telangana'), (25, 'Tripura'), (26, 'Uttar Pradesh'), (27, 'Uttarakhand'), (28, 'West Bengal'), (29, 'Andaman and Nicobar Islands'), (30, 'Chandigarh'), (31, 'Dadra and Nagar Haveli and Daman and Diu'), (32, 'Delhi'), (33, 'Lakshadweep'), (34, 'Puducherry')], default=0)),
                ('medium', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi')], default='english', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='storage/user_profile/student/profile_images/')),
            ],
        ),
    ]
