# Generated by Django 5.1.1 on 2024-09-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_role'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('coaching', 'Coaching'), ('evaluator', 'Evaluator'), ('reviewer', 'Reviewer'), ('enquiry', 'Enquiry'), ('admin', 'Admin'), ('superuser', 'Superuser')], max_length=20, null=True),
        ),
    ]
