# Generated by Django 5.1.1 on 2024-09-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('attempt', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('medium', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi')], default='english', max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.IntegerField(blank=True, default=0)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('Num_of_Prelims', models.IntegerField(blank=True, default=0)),
                ('Num_of_Mains', models.IntegerField(blank=True, default=0)),
                ('Num_of_Interviews', models.IntegerField(blank=True, default=0)),
                ('medium', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi')], default='english', max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('optional', models.CharField(choices=[('agriculture', 'Agriculture'), ('animal husbandry and veterinary science', 'Animal Husbandry and Veterinary Science'), ('anthropology', 'Anthropology'), ('botany', 'Botany'), ('chemistry', 'Chemistry'), ('civil engineering', 'Civil Engineering'), ('commerce & accountancy', 'Commerce & Accountancy'), ('economics', 'Economics'), ('electrical engineering', 'Electrical Engineering'), ('geography', 'Geography'), ('geology', 'Geology'), ('history', 'History'), ('law', 'Law'), ('management', 'Management'), ('mathematics', 'Mathematics'), ('mechanical engineering', 'Mechanical Engineering'), ('medical science', 'Medical Science'), ('philosophy', 'Philosophy'), ('physics', 'Physics'), ('political science & international relations', 'Political Science & International Relations'), ('psychology', 'Psychology'), ('public administration', 'Public Administration'), ('sociology', 'Sociology'), ('statistics', 'Statistics'), ('zoology', 'Zoology'), ('hindi literature', 'Hindi Literature'), ('assamese literature', 'Assamese Literature'), ('bengali literature', 'Bengali Literature'), ('bodo literature', 'Bodo Literature'), ('dogri literature', 'Dogri Literature'), ('gujarati literature', 'Gujarati Literature'), ('kannada literature', 'Kannada Literature'), ('kashmiri literature', 'Kashmiri Literature'), ('konkani literature', 'Konkani Literature'), ('maithili literature', 'Maithili Literature'), ('malayalam literature', 'Malayalam Literature'), ('manipuri literature', 'Manipuri Literature'), ('marathi literature', 'Marathi Literature'), ('nepali literature', 'Nepali Literature'), ('oriya literature', 'Oriya Literature'), ('punjabi literature', 'Punjabi Literature'), ('sanskrit literature', 'Sanskrit Literature'), ('santhali literature', 'Santhali Literature'), ('sindhi literature', 'Sindhi Literature'), ('tamil literature', 'Tamil Literature'), ('telugu literature', 'Telugu Literature'), ('urdu literature', 'Urdu Literature'), ('english literature', 'English Literature')], default='Not Selected', max_length=90)),
                ('rank_secured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('medium', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi')], default='english', max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('attempt', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('medium', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi')], default='english', max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
            ],
        ),
    ]
