# Generated by Django 5.1.1 on 2024-09-16 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorModel',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Phone_number', models.IntegerField(blank=True, default=0)),
                ('Num_of_Prelims', models.IntegerField(blank=True, default=0)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
            ],
        ),
    ]
