# Generated by Django 5.1.1 on 2024-09-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluator',
            name='courseenroll',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='courseenroll',
        ),
    ]
