# Generated by Django 5.1.1 on 2024-09-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_evaluator_courseenroll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluator',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='attempt',
        ),
    ]
