# Generated by Django 5.1.1 on 2024-09-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_evaluator_num_of_interviews_evaluator_num_of_mains_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaching',
            name='attempt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='Num_of_Interviews',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='Num_of_Mains',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='Num_of_Prelims',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='attempt',
            field=models.CharField(max_length=50),
        ),
    ]
