# Generated by Django 5.1.1 on 2024-09-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_coaching_attempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaching',
            name='courseenroll',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courseenroll',
        ),
    ]
