subject_integer = {
    'notselected':0,
    'agriculture': 1,
    'animal_husbandry_and_veterinary_science': 2,
    'anthropology': 3,
    'botany': 4,
    'chemistry': 5,
    'civil_engineering': 6,
    'commerce_&_accountancy': 7,
    'economics': 8,
    'electrical_engineering': 9,
    'geography': 10,
    'geology': 11,
    'history': 12,
    'law': 13,
    'management': 14,
    'mathematics': 15,
    'mechanical_engineering': 16,
    'medical_science': 17,
    'philosophy': 18,
    'physics': 19,
    'political_science_&_international_relations': 20,
    'psychology': 21,
    'public_administration': 22,
    'sociology': 23,
    'statistics': 24,
    'zoology': 25,
    'hindi_literature': 26,
    'assamese_literature': 27,
    'bengali_literature': 28,
    'bodo_literature': 29,
    'dogri_literature': 30,
    'gujarati_literature': 31,
    'kannada_literature': 32,
    'kashmiri_literature': 33,
    'konkani_literature': 34,
    'maithili_literature': 35,
    'malayalam_literature': 36,
    'manipuri_literature': 37,
    'marathi_literature': 38,
    'nepali_literature': 39,
    'oriya_literature': 40,
    'punjabi_literature': 41,
    'sanskrit_literature': 42,
    'santhali_literature': 43,
    'sindhi_literature': 44,
    'tamil_literature': 45,
    'telugu_literature': 46,
    'urdu_literature': 47,
    'english_literature': 48
}

optional_subjects = [
    (subject_integer['notselected'], 'Not Selected'),
    (subject_integer['agriculture'], 'Agriculture'),
    (subject_integer['animal_husbandry_and_veterinary_science'], 'Animal Husbandry and Veterinary Science'),
    (subject_integer['anthropology'], 'Anthropology'),
    (subject_integer['botany'], 'Botany'),
    (subject_integer['chemistry'], 'Chemistry'),
    (subject_integer['civil_engineering'], 'Civil Engineering'),
    (subject_integer['commerce_&_accountancy'], 'Commerce & Accountancy'),
    (subject_integer['economics'], 'Economics'),
    (subject_integer['electrical_engineering'], 'Electrical Engineering'),
    (subject_integer['geography'], 'Geography'),
    (subject_integer['geology'], 'Geology'),
    (subject_integer['history'], 'History'),
    (subject_integer['law'], 'Law'),
    (subject_integer['management'], 'Management'),
    (subject_integer['mathematics'], 'Mathematics'),
    (subject_integer['mechanical_engineering'], 'Mechanical Engineering'),
    (subject_integer['medical_science'], 'Medical Science'),
    (subject_integer['philosophy'], 'Philosophy'),
    (subject_integer['physics'], 'Physics'),
    (subject_integer['political_science_&_international_relations'], 'Political Science & International Relations'),
    (subject_integer['psychology'], 'Psychology'),
    (subject_integer['public_administration'], 'Public Administration'),
    (subject_integer['sociology'], 'Sociology'),
    (subject_integer['statistics'], 'Statistics'),
    (subject_integer['zoology'], 'Zoology'),
    (subject_integer['hindi_literature'], 'Hindi Literature'),
    (subject_integer['assamese_literature'], 'Assamese Literature'),
    (subject_integer['bengali_literature'], 'Bengali Literature'),
    (subject_integer['bodo_literature'], 'Bodo Literature'),
    (subject_integer['dogri_literature'], 'Dogri Literature'),
    (subject_integer['gujarati_literature'], 'Gujarati Literature'),
    (subject_integer['kannada_literature'], 'Kannada Literature'),
    (subject_integer['kashmiri_literature'], 'Kashmiri Literature'),
    (subject_integer['konkani_literature'], 'Konkani Literature'),
    (subject_integer['maithili_literature'], 'Maithili Literature'),
    (subject_integer['malayalam_literature'], 'Malayalam Literature'),
    (subject_integer['manipuri_literature'], 'Manipuri Literature'),
    (subject_integer['marathi_literature'], 'Marathi Literature'),
    (subject_integer['nepali_literature'], 'Nepali Literature'),
    (subject_integer['oriya_literature'], 'Oriya Literature'),
    (subject_integer['punjabi_literature'], 'Punjabi Literature'),
    (subject_integer['sanskrit_literature'], 'Sanskrit Literature'),
    (subject_integer['santhali_literature'], 'Santhali Literature'),
    (subject_integer['sindhi_literature'], 'Sindhi Literature'),
    (subject_integer['tamil_literature'], 'Tamil Literature'),
    (subject_integer['telugu_literature'], 'Telugu Literature'),
    (subject_integer['urdu_literature'], 'Urdu Literature'),
    (subject_integer['english_literature'], 'English Literature')
]
