state_integer = {
    'notselected':0,
    'andhra_pradesh': 1,
    'arunachal_pradesh': 2,
    'assam': 3,
    'bihar': 4,
    'chhattisgarh': 5,
    'goa': 6,
    'gujarat': 7,
    'haryana': 8,
    'himachal_pradesh': 9,
    'jharkhand': 10,
    'karnataka': 11,
    'kerala': 12,
    'madhya_pradesh': 13,
    'maharashtra': 14,
    'manipur': 15,
    'meghalaya': 16,
    'mizoram': 17,
    'nagaland': 18,
    'odisha': 19,
    'punjab': 20,
    'rajasthan': 21,
    'sikkim': 22,
    'tamil_nadu': 23,
    'telangana': 24,
    'tripura': 25,
    'uttar_pradesh': 26,
    'uttarakhand': 27,
    'west_bengal': 28,
    'andaman_and_nicobar_islands': 29,
    'chandigarh': 30,
    'dadra_and_nagar_haveli_and_daman_and_diu': 31,
    'delhi': 32,
    'lakshadweep': 33,
    'puducherry': 34
}

states = [
    (state_integer['notselected'], 'Not Selected'),
    (state_integer['andhra_pradesh'], 'Andhra Pradesh'),
    (state_integer['arunachal_pradesh'], 'Arunachal Pradesh'),
    (state_integer['assam'], 'Assam'),
    (state_integer['bihar'], 'Bihar'),
    (state_integer['chhattisgarh'], 'Chhattisgarh'),
    (state_integer['goa'], 'Goa'),
    (state_integer['gujarat'], 'Gujarat'),
    (state_integer['haryana'], 'Haryana'),
    (state_integer['himachal_pradesh'], 'Himachal Pradesh'),
    (state_integer['jharkhand'], 'Jharkhand'),
    (state_integer['karnataka'], 'Karnataka'),
    (state_integer['kerala'], 'Kerala'),
    (state_integer['madhya_pradesh'], 'Madhya Pradesh'),
    (state_integer['maharashtra'], 'Maharashtra'),
    (state_integer['manipur'], 'Manipur'),
    (state_integer['meghalaya'], 'Meghalaya'),
    (state_integer['mizoram'], 'Mizoram'),
    (state_integer['nagaland'], 'Nagaland'),
    (state_integer['odisha'], 'Odisha'),
    (state_integer['punjab'], 'Punjab'),
    (state_integer['rajasthan'], 'Rajasthan'),
    (state_integer['sikkim'], 'Sikkim'),
    (state_integer['tamil_nadu'], 'Tamil Nadu'),
    (state_integer['telangana'], 'Telangana'),
    (state_integer['tripura'], 'Tripura'),
    (state_integer['uttar_pradesh'], 'Uttar Pradesh'),
    (state_integer['uttarakhand'], 'Uttarakhand'),
    (state_integer['west_bengal'], 'West Bengal'),
    (state_integer['andaman_and_nicobar_islands'], 'Andaman and Nicobar Islands'),
    (state_integer['chandigarh'], 'Chandigarh'),
    (state_integer['dadra_and_nagar_haveli_and_daman_and_diu'], 'Dadra and Nagar Haveli and Daman and Diu'),
    (state_integer['delhi'], 'Delhi'),
    (state_integer['lakshadweep'], 'Lakshadweep'),
    (state_integer['puducherry'], 'Puducherry')
]
