# Generated by Django 5.1.1 on 2024-09-16 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluator',
            name='User',
        ),
        migrations.AddField(
            model_name='evaluator',
            name='id',
            field=models.BigAutoField(auto_created=True, default=datetime.datetime(2024, 9, 16, 13, 42, 1, 993493, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
