# Generated by Django 5.1.1 on 2024-09-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
