# Generated by Django 5.1.1 on 2024-09-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_otp_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='id',
            field=models.BigAutoField(auto_created=True, default=11, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
